name: CI

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build_test:
    name: 🚴 Build + Lint + Test 🚴  # Match the name below (8398a7/action-slack).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate typings
        run: pnpm generate:type
        env:
          APP_GRAPHQL_CODEGEN_ENDPOINT: './backend/schema.graphql'

      - name: Lint CSS
        run: pnpm lint:css

      - name: Lint JS
        run: pnpm lint:js

      - name: Build
        run: pnpm build
        env:
          APP_ENVIRONMENT: 'CI'
          APP_GRAPHQL_API_DOMAIN: 'https://random-graphql-api-endpoint.com'
          APP_REST_API_DOMAIN: 'https://random-graphql-api-endpoint.com'
