name: CI

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build_test:
    name: 🚴 Build + Lint + Test 🚴  # Match the name below (8398a7/action-slack).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint CSS
        run: pnpm lint:css

      - name: Lint JS
        run: pnpm lint:js

      - name: Build
        run: pnpm build
        env:
          APP_ENVIRONMENT: 'ci'
          APP_GRAPHQL_API_ENDPOINT: 'https://random-graphql-api-endpoint.com'
          APP_CSRF_TOKEN_KEY: 'random-csrf-token-key'
          APP_SENTRY_DSN: 'https://random-token@sentry.io'
          APP_SENTRY_TRACES_SAMPLE_RATE: 0.2
          APP_BING_API_KEY: 'random-bing-id'
          APP_MAPBOX_API_KEY: 'random-mapbox-key'
          APP_MAXAR_PREMIUM_API_KEY: 'random-maxar-premium-api-key'
          APP_MAXAR_STANDARD_API_KEY: 'random-maxar-standard-api-key'
