name: CI

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build_test:
    name: 🚴 Build + Lint + Test 🚴  # Match the name below (8398a7/action-slack).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version: '17.x'
          cache: 'yarn'

      - name: 🤞 Install dependencies 🧪
        run: yarn install --frozen-lockfile --prefer-offline

      - name: 🤞 Run Lint 🧪
        run: yarn lint

      - name: 🤞 Run Test 🧪
        run: yarn test --passWithNoTests

      - name: 🤞 Run Build 🧪
        run: yarn build
        env:
          REACT_APP_ENVIRONMENT: 'ci'
          REACT_APP_SENTRY_DSN: 'https://random-token@sentry.io'
          REACT_APP_SENTRY_TRACES_SAMPLE_RATE: 0.2
          REACT_APP_FIREBASE_API_KEY: 'random-firebase-key'
          REACT_APP_FIREBASE_AUTH_DOMAIN: 'https://random-firebase-domain.com/auth'
          REACT_APP_FIREBASE_DATABASE_URL: 'https://random-firebase-domain.com/database'
          REACT_APP_FIREBASE_PROJECT_ID: 'random-project-id'
          REACT_APP_FIREBASE_STORAGE_BUCKET: 'random-storage-bucket'
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: 'random-message-sender-id'
          REACT_APP_FIREBASE_APP_ID: 'random-app-id'
          REACT_APP_COMMUNITY_DASHBOARD_URL: 'https://random-community-dashboard.com/url'
          REACT_APP_IMAGE_BING_API_KEY: 'random-bing-id'
          REACT_APP_IMAGE_MAPBOX_API_KEY: 'random-mapbox-key'
          REACT_APP_IMAGE_MAXAR_PREMIUM_API_KEY: 'random-maxar-premium-api-key'
          # -- NOTE: not used and seems to be discontinued
          REACT_APP_IMAGE_MAXAR_STANDARD_API_KEY: 'random-maxar-standard-api-key'
